/**
 * Jama REST API
 * This is the documentation for the Jama REST API.
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { MetaListWrapper } from './metaListWrapper';
import { PageInfo } from './pageInfo';

export interface AbstractRestResponse {
	status?: number;

	statusReasonPhrase?: string;

	pageInfo?: PageInfo;

	headers?: { [key: string]: Array<string>; };

	meta?: MetaListWrapper;

}


