/**
 * Jama REST API
 * This is the documentation for the Jama REST API.
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AllowedResource } from './allowedResource';
import { Lock } from './lock';

export interface Attachment {
	lock: Lock;

	fileName: string;

	mimeType: string;

	fileSize: number;

	id: number;

	documentKey: string;

	globalId: string;

	/**
	 * ID of a project
	 */
	project: number;

	/**
	 * ID of an item type
	 */
	itemType: number;

	createdDate: Date;

	modifiedDate: Date;

	lastActivityDate: Date;

	/**
	 * ID of a user
	 */
	createdBy: number;

	/**
	 * ID of a user
	 */
	modifiedBy: number;

	/**
	 * A set of resources and allowed permissions
	 */
	resources: { [key: string]: AllowedResource; };

	/**
	 * A map of field names to field values e.g. {\"name\":\"Sample Item\", \"status\": 292, \"release\": 2, \"assigned\": 23}
	 */
	fields: { [key: string]: any; };

}


