/**
 * Jama REST API
 * This is the documentation for the Jama REST API.
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface BaselineOrigin {
	/**
	 * ID of a user
	 */
	project?: number;

	/**
	 * ID of an item
	 */
	item?: number;

	/**
	 * ID of a filter
	 */
	filter?: number;

	/**
	 * ID of a release
	 */
	release?: number;

}


