/**
 * Jama REST API
 * This is the documentation for the Jama REST API.
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface BaselineParent {
	/**
	 * Item ID and version number for an item
	 */
	item?: Array<number>;

	/**
	 * ID of a project
	 */
	project?: number;

}


