/**
 * Jama REST API
 * This is the documentation for the Jama REST API.
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CommentBody } from './commentBody';
import { CommentLocation } from './commentLocation';

export interface Comment {
	id: number;

	/**
	 * ID of a comment
	 */
	inReplyTo: number;

	createdDate: Date;

	/**
	 * ID of a user
	 */
	createdBy: number;

	/**
	 * ID of a user
	 */
	modifiedBy: number;

	deleted: boolean;

	status: Comment.StatusEnum;

	body: CommentBody;

	commentType: Comment.CommentTypeEnum;

	location: CommentLocation;

}

export namespace Comment {
	export type StatusEnum = 'OPEN' | 'CANCELLED' | 'COMPLETED';
	export type CommentTypeEnum =
		'GENERAL'
		| 'QUESTION'
		| 'PROPOSED_CHANGE'
		| 'ACCEPTED_COMMENT'
		| 'REJECTED_COMMENT'
		| 'ISSUE'
		| 'DECISION'
		| 'DECISION_REQUEST';
}


