/**
 * Jama REST API
 * This is the documentation for the Jama REST API.
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ContentDisposition {
	type?: string;

	parameters?: { [key: string]: string; };

	fileName?: string;

	creationDate?: Date;

	modificationDate?: Date;

	readDate?: Date;

	size?: number;

}


