/**
 * Jama REST API
 * This is the documentation for the Jama REST API.
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DerivedDataFailure } from './derivedDataFailure';

export interface DerivedDataHealthDetailsReport {
	numberItemsChecked?: number;

	numberChecksFailed?: number;

	failures?: Array<DerivedDataFailure>;

}


