/**
 * Jama REST API
 * This is the documentation for the Jama REST API.
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface FilterField {
	id: number;

	name: string;

	display: string;

	fieldDataType: FilterField.FieldDataTypeEnum;

}

export namespace FilterField {
	export type FieldDataTypeEnum =
		'INTEGER'
		| 'TEXT_FIELD'
		| 'TEXT_BOX'
		| 'PICKLIST'
		| 'DATE'
		| 'USER'
		| 'RELEASE'
		| 'BOOLEAN'
		| 'GROUP'
		| 'MULTI_SELECT'
		| 'ITEM_OF_TYPE'
		| 'URL'
		| 'ITEM_TYPE'
		| 'PROJECT'
		| 'STEPS'
		| 'TIME'
		| 'TEST_RUN_STATUS'
		| 'ITEM_OF_CATEGORY'
		| 'TEST_CASE_STATUS'
		| 'ACTIONS'
		| 'TAG'
		| 'DOWNSTREAM_RELATIONSHIP'
		| 'NO_DOWNSTREAM_RELATIONSHIP'
		| 'UPSTREAM_RELATIONSHIP'
		| 'NO_UPSTREAM_RELATIONSHIP'
		| 'CHANGE_REQUEST'
		| 'LOCATION'
		| 'QUERY_PARSER'
		| 'ADHOC'
		| 'HAS_TEST_CENTER_ITEM'
		| 'GLOBAL_ID';
}


