/**
 * Jama REST API
 * This is the documentation for the Jama REST API.
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { FilterField } from './filterField';
import { FilterQuery } from './filterQuery';

export interface FilterRule {
	field: FilterField;

	operator: FilterRule.OperatorEnum;

	values: Array<string>;

	/**
	 * ID of an item type
	 */
	itemType: number;

	subQuery: FilterQuery;

	rules: Array<FilterRule>;

}

export namespace FilterRule {
	export type OperatorEnum =
		'GROUP_OR'
		| 'GROUP_AND'
		| 'OR'
		| 'AND'
		| 'EQUALS'
		| 'EQUALS_DATE'
		| 'EQUALS_MULTI'
		| 'NOT_EQUALS'
		| 'NOT_EQUALS_DATE'
		| 'NOT_EQUALS_MULTI'
		| 'GREATER_THAN'
		| 'GREATER_THAN_DATE'
		| 'LESS_THAN'
		| 'LESS_THAN_DATE'
		| 'IN'
		| 'IS_TRUE'
		| 'IS_FALSE'
		| 'CONTAINS'
		| 'CONTAINS_WORD'
		| 'NOT_CONTAINS'
		| 'NOT_CONTAINS_WORD'
		| 'IS_ASSOCIATED_ITEM'
		| 'IS_ASSOCIATED_SUSPECT_ITEM'
		| 'IS_ASSOCIATED_NOT_SUSPECT_ITEM'
		| 'IS_BETWEEN'
		| 'HAS_ALL'
		| 'HAS_NONE'
		| 'IS_DIRECTLY_UNDER'
		| 'IS_UNDER'
		| 'IS_CURRENT_USER'
		| 'IS_EMPTY'
		| 'IS_NOT_EMPTY'
		| 'IS_NOT_DIRECTLY_UNDER'
		| 'IS_UNDER_OR_EQUAL'
		| 'IS_NOT_UNDER'
		| 'LOCATION_IS'
		| 'TEST_CENTER_RELATE'
		| 'SHARED_WITH'
		| 'NOT_SHARED_WITH'
		| 'IS_WITHIN_LAST';
}


