/**
 * Jama REST API
 * This is the documentation for the Jama REST API.
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BodyPart } from './bodyPart';
import { ContentDisposition } from './contentDisposition';
import { FormDataBodyPart } from './formDataBodyPart';
import { MediaType } from './mediaType';
import { MessageBodyWorkers } from './messageBodyWorkers';
import { MultiPart } from './multiPart';
import { ParameterizedHeader } from './parameterizedHeader';
import { Providers } from './providers';

export interface FormDataMultiPart {
	contentDisposition?: ContentDisposition;

	entity?: any;

	headers?: { [key: string]: Array<string>; };

	mediaType?: MediaType;

	messageBodyWorkers?: MessageBodyWorkers;

	parent?: MultiPart;

	providers?: Providers;

	bodyParts?: Array<BodyPart>;

	fields?: { [key: string]: Array<FormDataBodyPart>; };

	parameterizedHeaders?: { [key: string]: Array<ParameterizedHeader>; };

}


