/**
 * Jama REST API
 * This is the documentation for the Jama REST API.
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ItemTypeWidget {
	name: ItemTypeWidget.NameEnum;

	synchronize: boolean;

}

export namespace ItemTypeWidget {
	export type NameEnum =
		'ACTIVITIES'
		| 'RELATIONSHIPS'
		| 'SYNCHRONIZED_ITEMS'
		| 'ATTACHMENTS'
		| 'URLS'
		| 'TAGS'
		| 'HISTORY'
		| 'TEST_HISTORY_OLD'
		| 'SELENIUM'
		| 'CHANGE_REQUESTS'
		| 'FOLDER_LIST'
		| 'INSIDE_CHANGE_REQUEST'
		| 'ITEMS_WITH_ATTACHMENT'
		| 'TEST_RUNS'
		| 'TEST_CASE';
}


