/**
 * Jama REST API
 * This is the documentation for the Jama REST API.
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ItemTypeField } from './itemTypeField';
import { ItemTypeWidget } from './itemTypeWidget';

export interface ItemType {
	id: number;

	typeKey: string;

	display: string;

	displayPlural: string;

	description: string;

	image: string;

	category: ItemType.CategoryEnum;

	widgets: Array<ItemTypeWidget>;

	fields: Array<ItemTypeField>;

	system: boolean;

}

export namespace ItemType {
	export type CategoryEnum =
		'CORE'
		| 'ATTACHMENT'
		| 'COMPONENT'
		| 'SET'
		| 'SECTION'
		| 'TEXT'
		| 'TEST_PLAN'
		| 'TEST_CYCLE'
		| 'TEST_RUN'
		| 'TEST_CASE'
		| 'DEFECT';
}


