/**
 * Jama REST API
 * This is the documentation for the Jama REST API.
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Parent } from './parent';

export interface Location {
	sortOrder: number;

	globalSortOrder: number;

	sequence: string;

	parent: Parent;

}


