/**
 * Jama REST API
 * This is the documentation for the Jama REST API.
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface MetaWrapper {
	status?: MetaWrapper.StatusEnum;

	timestamp?: Date;

}

export namespace MetaWrapper {
	export type StatusEnum =
		'OK'
		| 'CREATED'
		| 'ACCEPTED'
		| 'NO_CONTENT'
		| 'RESET_CONTENT'
		| 'PARTIAL_CONTENT'
		| 'MOVED_PERMANENTLY'
		| 'FOUND'
		| 'SEE_OTHER'
		| 'NOT_MODIFIED'
		| 'USE_PROXY'
		| 'TEMPORARY_REDIRECT'
		| 'BAD_REQUEST'
		| 'UNAUTHORIZED'
		| 'PAYMENT_REQUIRED'
		| 'FORBIDDEN'
		| 'NOT_FOUND'
		| 'METHOD_NOT_ALLOWED'
		| 'NOT_ACCEPTABLE'
		| 'PROXY_AUTHENTICATION_REQUIRED'
		| 'REQUEST_TIMEOUT'
		| 'CONFLICT'
		| 'GONE'
		| 'LENGTH_REQUIRED'
		| 'PRECONDITION_FAILED'
		| 'REQUEST_ENTITY_TOO_LARGE'
		| 'REQUEST_URI_TOO_LONG'
		| 'UNSUPPORTED_MEDIA_TYPE'
		| 'REQUESTED_RANGE_NOT_SATISFIABLE'
		| 'EXPECTATION_FAILED'
		| 'INTERNAL_SERVER_ERROR'
		| 'NOT_IMPLEMENTED'
		| 'BAD_GATEWAY'
		| 'SERVICE_UNAVAILABLE'
		| 'GATEWAY_TIMEOUT'
		| 'HTTP_VERSION_NOT_SUPPORTED';
}


