/**
 * Jama REST API
 * This is the documentation for the Jama REST API.
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Relationship {
	id: number;

	/**
	 * ID of an item
	 */
	fromItem: number;

	/**
	 * ID of an item
	 */
	toItem: number;

	/**
	 * ID of a relationship type
	 */
	relationshipType: number;

	suspect: boolean;

}


