/**
 * Jama REST API
 * This is the documentation for the Jama REST API.
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface RequestDerivedDataHealthReport {
	reportType?: RequestDerivedDataHealthReport.ReportTypeEnum;

	repair?: boolean;

}

export namespace RequestDerivedDataHealthReport {
	export type ReportTypeEnum = 'TEST_CASE_STATUS' | 'CALCULATED' | 'ROLLUP' | 'RELATIONSHIP_STATS';
}


