/**
 * Jama REST API
 * This is the documentation for the Jama REST API.
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface RequestUser {
	/**
	 * Required when creating a new user (POST). Optional on update (PUT)
	 */
	username: string;

	/**
	 * Required when creating a new user (POST). Not valid on update (PUT)
	 */
	password: string;

	/**
	 * Required when creating a new user (POST). Optional on update (PUT)
	 */
	firstName: string;

	/**
	 * Required when creating a new user (POST). Optional on update (PUT)
	 */
	lastName: string;

	/**
	 * Required when creating a new user (POST). Optional on update (PUT)
	 */
	email: string;

	phone?: string;

	title?: string;

	location?: string;

	/**
	 * Required when creating a new user (POST). Optional on update (PUT)
	 */
	licenseType: RequestUser.LicenseTypeEnum;

}

export namespace RequestUser {
	export type LicenseTypeEnum =
		'NAMED'
		| 'FLOATING'
		| 'STAKEHOLDER'
		| 'FLOATING_COLLABORATOR'
		| 'RESERVED_COLLABORATOR'
		| 'FLOATING_REVIEWER'
		| 'RESERVED_REVIEWER'
		| 'NAMED_REVIEWER'
		| 'TEST_RUNNER'
		| 'EXPIRING_TRIAL'
		| 'INACTIVE';
}


