/**
 * Jama REST API
 * This is the documentation for the Jama REST API.
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { RequestCommentBody } from './requestCommentBody';
import { RequestCommentLocation } from './requestCommentLocation';

export interface RequestComment {
	/**
	 * ID of a comment
	 */
	inReplyTo?: number;

	body: RequestCommentBody;

	commentType?: RequestComment.CommentTypeEnum;

	location?: RequestCommentLocation;

}

export namespace RequestComment {
	export type CommentTypeEnum =
		'GENERAL'
		| 'QUESTION'
		| 'PROPOSED_CHANGE'
		| 'ACCEPTED_COMMENT'
		| 'REJECTED_COMMENT'
		| 'ISSUE'
		| 'DECISION'
		| 'DECISION_REQUEST';
}


