/**
 * Jama REST API
 * This is the documentation for the Jama REST API.
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface RequestPickListOption {
	description?: string;

	name: string;

	value?: string;

	color?: RequestPickListOption.ColorEnum;

	sortOrder?: number;

	default?: boolean;

}

export namespace RequestPickListOption {
	export type ColorEnum =
		'000000'
		| '3C3C3C'
		| '666666'
		| 'AAAAAA'
		| 'BBBBBB'
		| 'CCCCCC'
		| 'DDDDDD'
		| 'EEEEEE'
		| 'FFFFFF'
		| 'FF0000'
		| 'FF9933'
		| 'FFF800'
		| '00CC66'
		| '32ABD6'
		| '0066CC'
		| '003366'
		| '663399'
		| 'FF3399'
		| 'E39191'
		| 'FFCC66'
		| 'FFFF66'
		| '9CE78C'
		| '9BDFFF'
		| '66A3E0'
		| '335C85'
		| '9966FF'
		| 'FF66FF'
		| 'FFCCCC'
		| 'FFE9BC'
		| 'FFFFCC'
		| 'CCFFCC'
		| 'CCFFFF'
		| '99C2EB'
		| '99ADC2'
		| 'CAB4FF'
		| 'F7C0FF'
		| 'FBE4E3'
		| 'FFF4DB'
		| 'FFFFE1'
		| 'E6FFE1'
		| 'E9FFFF'
		| 'CCD6E0'
		| 'EAEAFF'
		| 'FDE3FF';
}


