/**
 * Jama REST API
 * This is the documentation for the Jama REST API.
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface RequestParent {
	/**
	 * ID of an item. If this is included, the item of this payload will be located at this parent item. If this is not included, the item will be located at the root of the project.
	 */
	item?: number;

	/**
	 * ID of an project. If this is included, the item of this payload will be located at the root of the project, and a parent item cannot be specified. This value will be inferred by the \"project\" property at the root of the payload when a parent location is not specified.
	 */
	project?: number;

}


