/**
 * Jama REST API
 * This is the documentation for the Jama REST API.
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface RequestRelationship {
	fromItem: number;

	toItem: number;

	/**
	 * Relationships will be created with the default type when providing a null or invalid relationship type
	 */
	relationshipType?: number;

}


