/**
 * Jama REST API
 * This is the documentation for the Jama REST API.
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface RequestPatchOperation {
	op: RequestPatchOperation.OpEnum;

	path: string;

	value?: any;

}

export namespace RequestPatchOperation {
	export type OpEnum = 'remove' | 'replace' | 'add';
}


