/**
 * Jama REST API
 * This is the documentation for the Jama REST API.
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface RequestProject {
	/**
	 * Not Required if isFolder is true
	 */
	projectKey: string;

	isFolder?: boolean;

	/**
	 * parent project
	 */
	parent?: number;

	/**
	 * A map of field names to field values e.g. {\"name\":\"Sample Project\", \"status\": 292, \"release\": 2, \"projectManager\": 23}
	 */
	fields: { [key: string]: any; };

}


