/**
 * Jama REST API
 * This is the documentation for the Jama REST API.
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface VersionedRelationship {
	id: number;

	/**
	 * ID of a version
	 */
	fromItem: Array<number>;

	/**
	 * ID of a version
	 */
	toItem: Array<number>;

	suspect: boolean;

	/**
	 * ID of a relationship type
	 */
	relationshipType: Array<any>;

}


