/**
 * Jama REST API
 * This is the documentation for the Jama REST API.
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Version {
	/**
	 * Item ID and version number for a versioned item
	 */
	versionedItem: Array<number>;

	type?: string;

	/**
	 * ID of an item
	 */
	item: number;

	versionNumber: number;

	changeDetails: string;

	comment: string;

	createdDate: Date;

	/**
	 * ID of a user
	 */
	createdBy: number;

}


