/**
 * Jama REST API
 * This is the documentation for the Jama REST API.
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Link } from './link';
import { MetaListWrapper } from './metaListWrapper';
import { WorkflowTransition } from './workflowTransition';

export interface WorkflowTransitionDataListWrapper {
	data?: Array<WorkflowTransition>;

	links?: { [key: string]: Link; };

	linked?: { [key: string]: { [key: string]: any; }; };

	meta?: MetaListWrapper;

}


